# Generated by Django 2.2 on 2020-06-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_type', models.PositiveSmallIntegerField(choices=[(1, 'setor A Funcionarios'), (2, 'setor B Geral'), (3, 'setor C Geral'), (4, 'setor D Geral')], verbose_name='Setores')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50, unique=True)),
                ('data', models.DateTimeField()),
                ('setor_type', models.PositiveSmallIntegerField(choices=[(1, 'Setor A Funcionarios'), (2, 'Setor B Geral'), (3, 'Setor C Geral'), (4, 'Setor D Geral')], verbose_name='Setor')),
                ('descrição', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('setor_type', models.PositiveSmallIntegerField(choices=[(1, 'Setor A Funcionarios'), (2, 'Setor B Geral'), (3, 'Setor C Geral'), (4, 'Setor D Geral')], null=True, verbose_name='Setor')),
                ('occurrence_type', models.PositiveSmallIntegerField(choices=[(1, 'Assalto / Furto'), (2, 'Batida / Sinistro'), (3, 'Estacionamento Indevido'), (4, 'Inundação'), (5, 'Dano ao Veiculo')], verbose_name='Motivo da Ocorrencia')),
                ('obs', models.TextField(verbose_name='Obersavões')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_normais', models.IntegerField()),
                ('vagas_especiais', models.IntegerField()),
                ('vagas_especiais_ocupadas', models.IntegerField()),
                ('vagas_normais_ocupadas', models.IntegerField()),
                ('setor_type', models.PositiveSmallIntegerField(choices=[(1, 'Setor A Funcionarios'), (2, 'Setor B Geral'), (3, 'Setor C Geral'), (4, 'Setor D Geral')], verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('proprietario', models.CharField(max_length=50, unique=True)),
                ('matricula', models.BigIntegerField(unique=True)),
                ('curso', models.CharField(max_length=50)),
                ('area_especial', models.BooleanField()),
            ],
        ),
    ]
