# Generated by Django 2.2.10 on 2020-06-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200602_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_normais', models.IntegerField()),
                ('vagas_especiais', models.IntegerField()),
                ('setor_type', models.PositiveSmallIntegerField(choices=[(1, 'Setor A Funcionarios'), (2, 'Setor B Geral'), (3, 'Setor C Geral'), (4, 'Setor D Geral')], verbose_name='Setor')),
            ],
        ),
    ]
