# Generated by Django 2.2.10 on 2020-06-03 01:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200602_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Funcionario Estacionamento'), (2, 'Rh'), (3, 'Gerente')], verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'O username só pode conter letras, números ou as caracteres @/./+/-/_', 'invalid')], verbose_name='Nome do Usuario'),
        ),
    ]
